### ISSUE TITLE
R10k stop responding causing continues deployments to be halted

### ISSUE THREAD

**Issue by maartenschalekamp** [puppetlabs/puppetserver-helm-chart#102]
## Describe the Bug
Our puppet codebase hosted on github and we using compilers with r10k. For some reason the r10k process randomly goes into not responding and causes continues deployment for 10k not to continue.

```
time="2022-02-04T07:45:00Z" level=warning msg="not starting: job is still running since 2022-02-04 04:55:00 +0000 UTC (2h50m0s elapsed)" iteration=175 job.command="/bin/sh -c /etc/puppetlabs/puppet/r10k_code_cronjob.sh" job.position=0 job.schedule="*/5 * * * *"
time="2022-02-04T07:50:00Z" level=warning msg="not starting: job is still running since 2022-02-04 04:55:00 +0000 UTC (2h55m0s elapsed)" iteration=175 job.command="/bin/sh -c /etc/puppetlabs/puppet/r10k_code_cronjob.sh" job.position=0 job.schedule="*/5 * * * *"
time="2022-02-04T07:55:00Z" level=warning msg="not starting: job is still running since 2022-02-04 04:55:00 +0000 UTC (3h0m0s elapsed)" iteration=175 job.command="/bin/sh -c /etc/puppetlabs/puppet/r10k_code_cronjob.sh" job.position=0 job.schedule="*/5 * * * *"
```

To resolve it I need to manually kill the r10k process on the r10k-code container or perform a rollout on the statefulset. 

## Expected Behavior
Well, expecting the process to complete and be available on the next run.

## Steps to Reproduce
Deploy and wait. :P

## Environment
 - Pupperserver image version tag: 7.5.0
 - Kubernetes node: v1.21.2-eks-55daa9d

## Additional Context
Doing a pkill on r10k the stacktrace as follow, not sure if this will be any useful.
```
~ $ pkill r10k
~ $
r10k: Runtime error: #<SignalException: SIGTERM>
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/puppetfile.rb:210:in `join'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/puppetfile.rb:210:in `each'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/puppetfile.rb:210:in `concurrent_accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/puppetfile.rb:184:in `accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/environment/with_modules.rb:84:in `block in accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/deploy/environment.rb:105:in `visit_environment'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/visitor.rb:24:in `visit'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/environment/with_modules.rb:79:in `accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/source/base.rb:70:in `block (2 levels) in accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/source/base.rb:69:in `each'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/source/base.rb:69:in `block in accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/deploy/environment.rb:80:in `visit_source'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/visitor.rb:24:in `visit'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/source/base.rb:68:in `accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/deployment.rb:108:in `block (2 levels) in accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/deployment.rb:107:in `each'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/deployment.rb:107:in `block in accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/deploy/environment.rb:60:in `visit_deployment'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/visitor.rb:24:in `visit'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/deployment.rb:106:in `accept'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/deploy/environment.rb:38:in `call'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/runner.rb:33:in `call'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/lib/r10k/action/cri_runner.rb:67:in `call'
/usr/lib/ruby/gems/2.5.0/gems/cri-2.15.11/lib/cri/command_dsl.rb:294:in `block in runner'
/usr/lib/ruby/gems/2.5.0/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
/usr/lib/ruby/gems/2.5.0/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
/usr/lib/ruby/gems/2.5.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
/usr/lib/ruby/gems/2.5.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
/usr/lib/ruby/gems/2.5.0/gems/r10k-3.8.0/bin/r10k:7:in `<top (required)>'
/usr/bin/r10k:23:in `load'
/usr/bin/r10k:23:in `<main>'
```

When comparing the debug2 output from the r10k that stopped and the r10k that completed the last bit is different. The output below added on where the not responding one does not have this>
```
[ - DEBUG] Module thread 47275400490780 exiting: queue empty
[ - DEBUG2] Starting process: ["git", "--git-dir", "/etc/puppetlabs/code/r10k_cache/https---github.com-garethr-garethr-docker.git", "rev-parse", "master^{commit}"]
[ - DEBUG2] Finished process:
Command: git --git-dir /etc/puppetlabs/code/r10k_cache/https---github.com-garethr-garethr-docker.git rev-parse master^{commit}
Stdout:
d8587b2affc98daf5d64e91992aff0a89c0ba751
Exit code: 0
[ - DEBUG2] Starting process: ["git", "--git-dir", "/etc/puppetlabs/code/environments/production/modules/docker/.git", "rev-parse", "HEAD^{commit}"]
[ - DEBUG2] Finished process:
Command: git --git-dir /etc/puppetlabs/code/environments/production/modules/docker/.git rev-parse HEAD^{commit}
Stdout:
d8587b2affc98daf5d64e91992aff0a89c0ba751
Exit code: 0
[ - DEBUG2] Starting process: ["git", "--git-dir", "/etc/puppetlabs/code/r10k_cache/https---github.com-jsok-puppet-vault.git", "rev-parse", "4aadbbd^{commit}"]
[ - DEBUG2] Finished process:
Command: git --git-dir /etc/puppetlabs/code/r10k_cache/https---github.com-jsok-puppet-vault.git rev-parse 4aadbbd^{commit}
Stdout:
4aadbbd72b792b91d6079e1f45c11f03b69f305b
Exit code: 0
[ - DEBUG2] Starting process: ["git", "--git-dir", "/etc/puppetlabs/code/environments/production/modules/vault/.git", "rev-parse", "HEAD^{commit}"]
[ - DEBUG2] Finished process:
Command: git --git-dir /etc/puppetlabs/code/environments/production/modules/vault/.git rev-parse HEAD^{commit}
Stdout:
4aadbbd72b792b91d6079e1f45c11f03b69f305b
Exit code: 0
[ - DEBUG2] Starting process: ["git", "--git-dir", "/etc/puppetlabs/code/environments/production/.git", "rev-parse", "HEAD^{commit}"]
[ - DEBUG2] Finished process:
Command: git --git-dir /etc/puppetlabs/code/environments/production/.git rev-parse HEAD^{commit}
Stdout:
7e18ae0642cd6a8a1a8dd4b9829c3daea53bc4a1
Exit code: 0
[ - DEBUG] Purging unmanaged environments for deployment...
[ - DEBUG1] Source puppet_repo in /etc/puppetlabs/code/environments manages contents ["XYZ", "production"]
[ - DEBUG1] No unmanaged contents in /etc/puppetlabs/code/environments, nothing to purge
```

This is maybe the wrong place to put this bug report. Not sure if there is maybe some issue just on my environment or setup. Otherwise would like to have an option to enable the `timeout` function on r10k to kill the process if it was running longer than x seconds, which can be configurable.

**Comment by vissieza** [comment]
Well. After updating r10k my issue seems to be resolve so this not required anymore.
